image: atlassian/default-image:latest

pipelines:
  branches:
    development:
      - step:
        script:
          - ssh optimalr@de7.fcomet.com -p17177
          - cd development && git pull origin development
          - cd panel.optimalrating.com && npm install && npm run build && cd ..
          - cd optimalrating.com && npm install && npm run build && cd ..
          - cd server.optimalrating && composer install && php artisan migrate && cd ..
          - exit