image: atlassian/default-image:latest

pipelines:

  branches:

    uat:

      - step:

          name: Deploy to Uat
      
          script:
            - cat ./deploy.sh | ssh -T optimalr@de7.fcomet.com -p17177
