/**
 *@author uveysservetoglu
 */


export const SET_DEFINITION = 'SET_DEFINITION';
export const SET_DEFINITION_ITEM = 'SET_DEFINITION_AFTER';

export const ADD_DEFINITION_ITEM = 'ADD_DEFINITION_ITEM';
export const ADD_DEFINITION_ITEM_AFTER = 'ADD_DEFINITION_ITEM_AFTER';

export const EMPTY_DEFINITION = 'EMPTY_DEFINITION';
export const DELETE_DEFINITION = 'DELETE_DEFINITION';

/**
 * Vuex Mutations - Types
 */
export default {
  SET_DEFINITION,
  SET_DEFINITION_ITEM,
  ADD_DEFINITION_ITEM,
  ADD_DEFINITION_ITEM_AFTER,
  EMPTY_DEFINITION,
  DELETE_DEFINITION
}